lib/strs_web/router.ex
defmodule StrsWeb.Router do
  use StrsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  scope "/", StrsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/users", UserController, :index
    resources "/users", UserController

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    resources "/session", SessionController, only: [:new, :create]

    get "/sessions", SessionController, :delete

    get "/bookings/new", BookingController, :new
    resources "/bookings", BookingController

    resources "/driver", DriverController
  end

  # Other scopes may use custom stacks.
  scope "/api", StrsWeb do
     pipe_through :api
     post "/users", UserController, :create
     resources "/users", UserController
     post "/login", SessionController, :create
     resources "/session", SessionController
     post "/bookings", BookingController, :create
  end
end

lib/strs/accounts/user.ex
defmodule Strs.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Strs.Accounts.{User, Encryption}

  schema "users" do
    field :email, :string
    field :first_name, :string
    field :last_name, :string
    field :password_hash, :string
    field :user_type, :integer
    ## add virtual feilds
    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true
    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:first_name, :last_name, :email, :password, :user_type])
    |> validate_required([:first_name, :last_name, :email, :password, :user_type])
    |> validate_format(:email, ~r/@/)
    |> unique_constraint(:email, message: "Email should be unique")
    |> validate_length(:password, min: 6)
    |> validate_confirmation(:password)
    |> encrypt_password
  end

  defp encrypt_password(changeset) do
    password = get_change(changeset, :password)

    if password do
      encrypted_password = Encryption.hash_password(password)
      put_change(changeset, :password_hash, encrypted_password)
    else
      changeset
    end
  end
end

lib/strs_web/controllers/user_controller.ex
defmodule StrsWeb.UserController do
  use StrsWeb, :controller

  alias Strs.Accounts
  alias Strs.Accounts.User
  alias Strs.Taxi
  #alias Strs.Taxi


  # defp check_auth(conn, _args) do
  #   if user_id = get_session(conn, :current_user) do
  #     current_user = Accounts.get_user!(user_id)

  #     conn
  #     |> assign(:current_user, current_user)
  #   else
  #     conn
  #     |> put_flash(:error, "You need to signed in to access this page")
  #     |> redirect(to: "/")
  #     |> halt()
  #   end
  # end

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn,user_params) do

    case Accounts.create_user(user_params) do
      {:ok, user} ->
        if user_params["user_type"] == "1" do
            driver_params = %{user_id: user.id, status: true, location: "Narva maantee 25, 51013 Tartu, Estonia"}
            Taxi.create_driver(driver_params)
        end
        put_status(conn, 200)
        |> json(%{msg: "We cannot serve your request in this moment"})
        # |> put_flash(:info, "User created successfully.")
        # |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end

  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)

    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

lib/strs_web/views/user_view.ex
defmodule StrsWeb.UserView do
  use StrsWeb, :view
end

lib/strs_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/strs_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :first_name, class: "control-label" %>
    <%= text_input f, :first_name, class: "form-control" %>
    <%= error_tag f, :first_name %>
  </div>
  <div class="form-group">
    <%= label f, :last_name, class: "control-label" %>
    <%= text_input f, :last_name, class: "form-control" %>
    <%= error_tag f, :last_name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= text_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, class: "control-label" %>
    <%= text_input f, :password_confirmation, class: "form-control" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  select(form, :role, ["Admin": "admin", "User": "user"])
#=> <select id="user_role" name="user[role]">
    <option value="admin">Admin</option>
    <option value="user">User</option>
    </select>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/strs_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
      
      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: user_path(@conn, :new) %></span>

lib/strs_web/templates/user/new.html.eex
<div id="app" >
    <register></register>
<div>
<%# <%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %> 

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/strs_web/templates/user/show.html.eex
<div class="container">
        <div class="row">
            <div class="col-06">
                  <div class="card">

                    <div class="card-body">
                        <div class="card-title mb-4">
                          <div class="d-flex justify-content-start">
                            <div class="ml-auto">
                                <%= link "Book Ride", to: booking_path(@conn, :new) %>
                            </div>
                          </div>  
                        </div>
                    </div>
                  </div>      

                </div>

            <div class="col-10">
                <div class="card">

                    <div class="card-body">
                        <div class="card-title mb-4">
                            <div class="d-flex justify-content-start">
                                <div class="image-container">
                                    <img src="http://placehold.it/150x150" id="imgProfile" style="width: 150px; height: 150px" class="img-thumbnail" />
                                    <div class="middle">
                                        <input type="file" style="display: none;" id="profilePicture" name="file" />
                                    </div>
                                </div>
                                <div class="userData ml-3">
                                    <h2 class="d-block" style="font-size: 1.5rem; font-weight: bold"><%= @user.first_name %> <%= @user.last_name %></h2>
                                    <h6 class="d-block"><%= @user.email %></h6>
                                    
                                </div>

                            </div>
                        </div>
                        
                    </div>

                </div>
                
            </div>
        </div>
    </div>