lib/strs_web/router.ex
defmodule StrsWeb.Router do
  use StrsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  scope "/", StrsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/users", UserController, :index
    resources "/users", UserController

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    resources "/session", SessionController, only: [:new, :create]

    get "/sessions", SessionController, :delete

    get "/bookings/new", BookingController, :new
    resources "/bookings", BookingController

    resources "/driver", DriverController
  end

  # Other scopes may use custom stacks.
  scope "/api", StrsWeb do
     pipe_through :api
     post "/users", UserController, :create
     resources "/users", UserController
     post "/login", SessionController, :create
     resources "/session", SessionController
     post "/bookings", BookingController, :create
  end
end

lib/strs_web/views/layout_view.ex
defmodule StrsWeb.LayoutView do
  use StrsWeb, :view
end

lib/strs_web/templates/layout/_navbar.html.eex
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="/">
          
          <img src="/images/strslogo/STRS-Bold.png" alt="" title="" style="width:100px"></a>
      </h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <%= if logged_in?(@conn) do %>
          <%= if current_user(@conn).user_type == 1 do %>
            Welcome Captain, <%= String.upcase(current_user(@conn).first_name <> " " <> current_user(@conn).last_name) %>
            <%= link "Logout", to: session_path(@conn, :delete), class: "btn btn-warning" %>
          <%= else %>
            Welcome, <%= String.upcase(current_user(@conn).first_name <> " " <> current_user(@conn).last_name) %>
            <%= link "Logout", to: session_path(@conn, :delete), class: "btn btn-warning" %>
          <% end %>
        <%= else %>
          <a class="p-2 text-dark" href="/login">Sign in</a>

          <a class="btn btn-outline-primary" href="/users/new">Sign up to Ride</a>
          <a class="btn btn-outline-success" href="#">Register as Captain</a>
        <% end %>
      </nav>
  </div>

lib/strs_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Strs!</title>
    
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet">
  <style>
    .login-form {
    padding:20px;
    padding-top:20px;
    background-color: #e3e6ea;
  }
  </style>
  </head>

  <body>
    <div class="container">
      <%= render "_navbar.html", conn: @conn %>

      <%# <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) </p> %>
      <%# <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error)</p> %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>